# SPDX-FileCopyrightText: © 2022 The Accrescent Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Bump MIN_TIMESTAMP

on:
  schedule:
    - cron: '0 10 28 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update Constants.kt
        env:
          FILE: app/src/main/java/app/accrescent/client/data/Constants.kt
          CONSTANT: 'const val MIN_TIMESTAMP: Long'
        run: |
          TIMESTAMP=$(curl -s https://repo.accrescent.app/repodata.1.json | jq '.timestamp')
          sed -i -E "s/^$CONSTANT = [[:digit:]]*$/$CONSTANT = $TIMESTAMP/" $FILE
      - name: Create pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        env:
          message: Bump MIN_TIMESTAMP
        with:
          title: ${{ env.message }}
          commit-message: ${{ env.message }}
          delete-branch: true
