// SPDX-FileCopyrightText: © 2021 The Accrescent Contributors
//
// SPDX-License-Identifier: Apache-2.0

package app.accrescent.client.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8B2EC0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF5D9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF30004A)
val md_theme_light_secondary = Color(0xFF68596E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0DCF4)
val md_theme_light_onSecondaryContainer = Color(0xFF231728)
val md_theme_light_tertiary = Color(0xFF815252)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD9)
val md_theme_light_onTertiaryContainer = Color(0xFF331112)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEADFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B444D)
val md_theme_light_outline = Color(0xFF7D747E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF332F33)
val md_theme_light_inversePrimary = Color(0xFFE6B4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8B2EC0)

val md_theme_dark_primary = Color(0xFFE6B4FF)
val md_theme_dark_onPrimary = Color(0xFF4F0076)
val md_theme_dark_primaryContainer = Color(0xFF7100A6)
val md_theme_dark_onPrimaryContainer = Color(0xFFF5D9FF)
val md_theme_dark_secondary = Color(0xFFD3C0D8)
val md_theme_dark_onSecondary = Color(0xFF382C3E)
val md_theme_dark_secondaryContainer = Color(0xFF4F4255)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0DCF4)
val md_theme_dark_tertiary = Color(0xFFF4B7B7)
val md_theme_dark_onTertiary = Color(0xFF4C2526)
val md_theme_dark_tertiaryContainer = Color(0xFF663B3C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE8E0E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE8E0E5)
val md_theme_dark_surfaceVariant = Color(0xFF4B444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CE)
val md_theme_dark_outline = Color(0xFF978E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE8E0E5)
val md_theme_dark_inversePrimary = Color(0xFF8B2EC0)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE6B4FF)

val seed = Color(0xFF7100A6)
